export type SunriseMilestone = "html" | "css" | "js" | null;

export type SunriseStep = {
	id: number;
	slug: `step${number}`;
	title: string;
	goal: string;
	estimatedTime: string;
	congratsMessage?: string;
	milestoneComplete: SunriseMilestone;
	checklist: string[];
	screenshot?: string;
};

export const sunriseSteps: SunriseStep[] = [
	{
		id: 1,
		slug: "step1",
		title: "Downloading VS Code",
		goal: "Download and set up VS Code Editor",
		estimatedTime: "3 min",
		milestoneComplete: null,
		checklist: [
			"Go to code.visualstudio.com/download",
			"Download VS Code for your computer",
			"Open VS Code - that's all!",
		],
		screenshot: "/imgs/guidestep1.png",
	},
	{
		id: 2,
		slug: "step2",
		title: "Create a Github Account",
		goal: "Go to github and create an account so that we can create a repository in the next step",
		estimatedTime: "4 min",
		milestoneComplete: null,
		checklist: [
			"Go to https://github.com/signup",
			"Log in or Sign up for Github",
		],
		screenshot: "/imgs/guidestep2.png",
	},
	{
		id: 3,
		slug: "step3",
		title: "Create a Github Repo",
		goal: "Create a Github Repo by going to Repositories and clicking New",
		estimatedTime: "5 min",
		milestoneComplete: null,
		checklist: [
			"First log into your account",
			"Go to Repositories and click New or to go https://github.com/new",
			"Name the Repo - no need to change anything else - and click create.",
		],
		screenshot: "/imgs/guidestep3.png",
	},
	{
		id: 4,
		slug: "step4",
		title: "Setting up the Project",
		goal: "Creating the initial files we would need to create a project",
		estimatedTime: "5 min",
		milestoneComplete: null,
		checklist: [
			"Open a folder in the VS Code",
			"Create index.html",
			"Create styles.css",
			"Create script.js",
		],
		screenshot: "/imgs/guidestep4.png",
	},
	{
		id: 5,
		slug: "step5",
		title: "Adding HTML Base",
		goal: "Adding the skeleton template for HTML file",
		estimatedTime: "4 min",
		milestoneComplete: null,
		checklist: [
			"Copy over this initial HTML template.",
			"This temaplte is something that every HTML page has in order to start with the website",
		],
		screenshot: "/imgs/guidestep5.png",
	},
	{
		id: 6,
		slug: "step6",
		title: "Container Elements",
		goal: "Learn about container elements",
		estimatedTime: "4 min",
		milestoneComplete: null,
		checklist: [
			"Add <header></header>",
			"Add <main></main>",
			"Add <footer></footer>",
			"Add <div></div> inside of the <main></main>",
			"Those are Container Elements, they do not have any display on the webpage, they are only there to contain other elements on the page",
		],
		screenshot: "/imgs/guidestep6.png",
	},
	{
		id: 7,
		slug: "step7",
		title: "Headings",
		goal: "Learn about adding headings in HTML",
		estimatedTime: "4 min",
		milestoneComplete: null,
		checklist: [
			"Add an <h1></h1>",
			"Add an <h2></h2>",
			"h1 stands for heading 1, which is the largest one, there are total of 6",
			"h2 is usually used as a subheading, which is heading 2",
		],
		screenshot: "/imgs/guidestep7.png",
	},
	{
		id: 8,
		slug: "step8",
		title: "Checkout your Website",
		goal: "View the website on the web",
		estimatedTime: "3 min",
		milestoneComplete: null,
		checklist: [
			"Click on index.html and select copy path",
			"Paste the copied path into the browser",
			"You should be able to see something like this",
		],
		screenshot: "/imgs/guidestep8.png",
	},
	{
		id: 9,
		slug: "step9",
		title: "Add lists",
		goal: "Add two of the lists to the website",
		estimatedTime: "4 min",
		milestoneComplete: null,
		checklist: [
			"Add an ol and an ul elements inside a div",
			"Inside both of those elements add an li elements.",
			"ol stands for ordered list, and ul stands for unordered list. Li stands for list item.",
		],
		screenshot: "/imgs/guidestep9.png",
	},
	{
		id: 10,
		slug: "step10",
		title: "Add an Image",
		goal: "Adding images to the web page",
		estimatedTime: "6 min",
		milestoneComplete: null,
		checklist: [
			"Create imgs folder",
			"Add an image to the imgs folder",
			"Add an img tag with the path to the image",
		],
		screenshot: "/imgs/guidestep10.png",
	},
	{
		id: 11,
		slug: "step11",
		title: "Adding Links",
		goal: "Add a link to the website",
		estimatedTime: "2 min",
		milestoneComplete: null,
		checklist: [
			"Add an anchor tag which is <a>",
			"In href add a link you'd like",
		],
		screenshot: "/imgs/guidestep11.png",
	},
	{
		id: 12,
		slug: "step12",
		title: "Link the CSS",
		goal: "Connect the CSS with the HTML.",
		estimatedTime: "5 min",
		milestoneComplete: null,
		checklist: [
			"Add a link in the head of the HTML",
			"Set the link to be relation stylesheet and link to the css file",
		],
		screenshot: "/imgs/guidestep12.png",
	},
	{
		id: 13,
		slug: "step13",
		title: "Basic Styles",
		goal: "Add basic styles like font family and direction",
		estimatedTime: "5 min",
		milestoneComplete: null,
		checklist: [
			"Copy over this CSS",
			"This changes the direction to center everything, and also the font family",
		],
		screenshot: "/imgs/guidestep13.png",
	},
	{
		id: 14,
		slug: "step14",
		title: "More CSS",
		goal: "Use margin, colors, and sizing",
		estimatedTime: "6 min",
		milestoneComplete: null,
		checklist: [
			"Add background colors and the text color",
			"Style the headings",
		],
		screenshot: "/imgs/guidestep14.png",
	},
	{
		id: 15,
		slug: "step15",
		title: "Edit the Image",
		goal: "Adit the image size and round it",
		estimatedTime: "5 min",
		milestoneComplete: null,
		checklist: ["Set width to 600px", "set border radius to 20px"],
		screenshot: "/imgs/guidestep15.png",
	},
	{
		id: 16,
		slug: "step16",
		title: "Link the Javascript",
		goal: "Connect the Javascript to the HTML.",
		estimatedTime: "5 min",
		milestoneComplete: null,
		checklist: ["Add script tag", "Add the path to your javascript file."],
		screenshot: "/imgs/guidestep16.png",
	},
	{
		id: 17,
		slug: "step17",
		title: "Create a function",
		goal: "Create a JavaScript function to fun on click",
		estimatedTime: "6 min",
		milestoneComplete: null,
		checklist: ["Create a function", "Inside of the function create an alert"],
		screenshot: "/imgs/guidestep17.png",
	},
	{
		id: 18,
		slug: "step18",
		title: "Connect the Javascript",
		goal: "Connect the Javascript function with the HTML button",
		estimatedTime: "5 min",
		milestoneComplete: null,
		checklist: [
			"Add a button element in your HTML",
			"Add an onclick to the button",
			"Put your function in the onclick field",
		],
		screenshot: "/imgs/guidestep18.png",
	},
	{
		id: 19,
		slug: "step19",
		title: "Test it out",
		goal: "Go on a website and check if the button works",
		estimatedTime: "6 min",
		milestoneComplete: null,
		checklist: [
			"Go to the website",
			"Click on the new button, and it should look something like this",
		],
		screenshot: "/imgs/guidestep19.png",
	},
	{
		id: 20,
		slug: "step20",
		title: "Adding it to Github",
		goal: "Review and push your finished basic code to github.",
		estimatedTime: "3 min",
		milestoneComplete: null,
		checklist: [
			"Click the Git icon on the left",
			"Write a commit messge",
			"Click commit",
			"If it asks 'Would you like to stage all your changes and commit them directly?' select yes",
		],
		screenshot: "/imgs/guidestep20.png",
	},
	{
		id: 21,
		slug: "step21",
		title: "Deploying",
		goal: "Creating a link for your site",
		estimatedTime: "3 min",
		milestoneComplete: null,
		checklist: [
			"Go to your github repo",
			"Click Settings",
			"Click Pages",
			"Click on the 'branch' and set it to main",
		],
		screenshot: "/imgs/guidestep21.png",
	},
	{
		id: 22,
		slug: "step22",
		title: "Deploying",
		goal: "Creating a link for your site",
		estimatedTime: "3 min",
		milestoneComplete: null,
		checklist: [
			"After 2-5 mins when you refresh the page there should be a link which would be leading to your website!",
		],
		screenshot: "/imgs/guidestep22.png",
	},
];

export function getSunriseStep(slug: string): SunriseStep | undefined {
	return sunriseSteps.find((step) => step.slug === slug);
}
